# Generated by Django 3.2.5 on 2021-09-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
    ]
