# Generated by Django 3.2.5 on 2021-09-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_department_department_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
