# Generated by Django 3.2.5 on 2021-09-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
