# Generated by Django 3.2.5 on 2021-10-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='officialdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeetype', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('employeegrade', models.CharField(max_length=30)),
                ('shift', models.CharField(max_length=30)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.designation')),
            ],
        ),
    ]
