# Generated by Django 3.2.5 on 2021-10-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_officialdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdetails',
            name='personal_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminapp.personaldetail'),
        ),
    ]
