# Generated by Django 3.2.5 on 2021-10-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_officialdetails_personal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialdetails',
            old_name='dob',
            new_name='doj',
        ),
    ]
