# Generated by Django 3.2.5 on 2021-10-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_contactdetails_department_designation_login_officialdetails_personaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='personal_id',
        ),
        migrations.DeleteModel(
            name='contactdetails',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='officialdetails',
        ),
        migrations.DeleteModel(
            name='personaldetail',
        ),
    ]
