# Generated by Django 3.2.5 on 2021-10-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_contactdetails_department_designation_document_login_officialdetails_personaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='personal_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminapp.personaldetail'),
        ),
    ]
