# Generated by Django 3.2.5 on 2021-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_document_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf', models.CharField(max_length=30)),
                ('ca', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('doc', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
