# Generated by Django 3.2.5 on 2021-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavetype', models.CharField(max_length=40)),
            ],
        ),
    ]
