# Generated by Django 3.2.5 on 2021-10-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_leavetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='personal_id',
        ),
        migrations.DeleteModel(
            name='leavetype',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='officialdetails',
            name='personal_id',
        ),
        migrations.DeleteModel(
            name='contactdetails',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='officialdetails',
        ),
        migrations.DeleteModel(
            name='personaldetail',
        ),
    ]
