# Generated by Django 3.2.5 on 2021-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_complaint_contactdetails_department_designation_document_employeedetail_leavetype_login_meeting_offi'),
    ]

    operations = [
        migrations.CreateModel(
            name='resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=30)),
                ('employeename', models.CharField(max_length=40)),
                ('resignationdate', models.CharField(max_length=40)),
                ('noticeperiod', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='officialdetails',
        ),
    ]
