# Generated by Django 3.2.5 on 2021-10-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_auto_20211027_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('promotiontitle', models.CharField(max_length=40)),
                ('promotiondate', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
            ],
        ),
    ]
