# Generated by Django 3.2.5 on 2021-10-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail'),
        ),
    ]
