# Generated by Django 3.2.5 on 2021-10-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_auto_20211028_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='employeeid',
        ),
        migrations.DeleteModel(
            name='promotion',
        ),
        migrations.DeleteModel(
            name='resignation',
        ),
    ]
