# Generated by Django 3.2.5 on 2021-10-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_auto_20211028_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=40)),
                ('resignationdate', models.CharField(max_length=40)),
                ('noticeperiod', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=60)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('promotiontitle', models.CharField(max_length=40)),
                ('promotiondate', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
    ]
