# Generated by Django 3.2.5 on 2021-10-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_promotion_resignation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='employeeid',
        ),
    ]
