# Generated by Django 3.2.5 on 2021-10-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_remove_resignation_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='employeeid',
        ),
        migrations.DeleteModel(
            name='resignation',
        ),
        migrations.DeleteModel(
            name='promotion',
        ),
    ]
