# Generated by Django 3.2.5 on 2021-11-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0038_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminlogin',
        ),
    ]
