# Generated by Django 3.2.5 on 2021-12-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_auto_20211208_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('fathersname', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('employeetype', models.CharField(max_length=30)),
                ('doj', models.DateField()),
                ('employeegrade', models.CharField(max_length=30)),
                ('shift', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=40)),
                ('resignationdate', models.CharField(max_length=40)),
                ('noticeperiod', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=60)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('promotiontitle', models.CharField(max_length=40)),
                ('promotiondate', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=40)),
                ('enddate', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=40)),
                ('remark', models.CharField(max_length=40)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
                ('leavecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('personal_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalemail', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employeedetail')),
            ],
        ),
    ]
