# Generated by Django 3.2.5 on 2021-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_contactdetails_document_employeedetail_leave_login_promotion_resignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='resignation',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
