# Generated by Django 3.2.5 on 2021-12-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0049_auto_20211208_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
