# Generated by Django 3.2.5 on 2021-12-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0051_auto_20211208_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='status',
        ),
    ]
