# Generated by Django 3.2.5 on 2021-12-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0052_remove_leavetype_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminlogin',
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employeeid',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leavecategory',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='meeting',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='employeeid',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='employeeid',
        ),
        migrations.DeleteModel(
            name='contactdetails',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='employeedetail',
        ),
        migrations.DeleteModel(
            name='leave',
        ),
        migrations.DeleteModel(
            name='leavetype',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='promotion',
        ),
        migrations.DeleteModel(
            name='resignation',
        ),
    ]
