# Generated by Django 3.2.5 on 2021-12-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0054_adminlogin_complaint_contactdetails_department_designation_document_employeedetail_leave_leavetype_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
