# Generated by Django 3.2.5 on 2021-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0057_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
