# Generated by Django 3.2.5 on 2021-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0058_leavetype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowancetype', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=40)),
            ],
        ),
    ]
