# Generated by Django 3.2.5 on 2021-12-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0060_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payroll',
        ),
    ]
