# Generated by Django 3.2.5 on 2021-12-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0062_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payroll',
        ),
    ]
