# Generated by Django 3.2.5 on 2021-12-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0064_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('occassion', models.CharField(max_length=40)),
                ('holidaytype', models.CharField(max_length=40)),
            ],
        ),
    ]
