# Generated by Django 3.2.5 on 2021-12-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0067_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='holiday',
        ),
    ]
