# Generated by Django 3.2.5 on 2021-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workinghours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.BigIntegerField()),
                ('date', models.DateField()),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField()),
                ('totalhours', models.TimeField()),
            ],
        ),
    ]
