# Generated by Django 3.2.5 on 2021-11-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='checkout',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='totalhours',
            field=models.TimeField(default=None, null=True),
        ),
    ]
