# Generated by Django 3.2.5 on 2021-11-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20211104_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workinghours',
        ),
    ]
