# Generated by Django 3.2.5 on 2021-11-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_workinghours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workinghours',
        ),
    ]
