# Generated by Django 3.2.5 on 2021-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0005_delete_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='workinghours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.BigIntegerField()),
                ('employeename', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField(default=None, null=True)),
                ('totalhours', models.TimeField(default=None, null=True)),
            ],
        ),
    ]
